package org.milaifontanals.info.projecte1;

import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.milaifontanals.info.projecte1.model.Canso;
/**
 *
 * @author Toni Puig
 */
public class Cansons extends javax.swing.JFrame {

    public BDCansons bdcan;
    private long id_can=-1;
    DefaultTableModel dtmCan = new DefaultTableModel();
    List<Canso> cansons=null;
    /**
     * Creates new form Cansons
     */
    public Cansons() {
        initComponents();
    }

    public long getId_can() {
        return id_can;
    }
    //public int llista_cansons(){}
    
    private void setTaula(){
        String[] cabecera = {"NOM", "DATA", "DURADA"};
        dtmCan.setColumnIdentifiers(cabecera);
        jTable_cansons.setModel(dtmCan);
        setDatos();
    }
    
    private void setDatos() {
        dtmCan.setNumRows(0);
        jTable_cansons.setModel(dtmCan);
        Object[] datos = new Object[dtmCan.getColumnCount()];
        try {
            bdcan=new BDCansons();
            cansons = bdcan.getLlistaCansons(jTextField_FragCanso.getText());
            for (int i = 0; i < cansons.size(); i++) {
                datos[0] = cansons.get(i).getTitol();
                datos[1] = cansons.get(i).getAnyCreacio();
                datos[2] = cansons.get(i).getDurada();
                dtmCan.addRow(datos);
            }
        } catch (GestorBDSportifyException e) {
            e.printStackTrace();
        }
        jTable_cansons.setModel(dtmCan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_general = new javax.swing.JPanel();
        jTextField_FragCanso = new javax.swing.JTextField();
        jLabel_canso = new javax.swing.JLabel();
        jScrollPane_cansons = new javax.swing.JScrollPane();
        jTable_cansons = new javax.swing.JTable();
        jBtn_selecionar = new javax.swing.JButton();
        jBtn_cancelar = new javax.swing.JButton();
        jBtn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_general.setBackground(new java.awt.Color(29, 185, 84));

        jLabel_canso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_canso.setForeground(java.awt.Color.white);
        jLabel_canso.setText("Cancion:");

        jTable_cansons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_cansons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_cansons.getTableHeader().setReorderingAllowed(false);
        jScrollPane_cansons.setViewportView(jTable_cansons);

        jBtn_selecionar.setText("SELECIONAR");
        jBtn_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_selecionarActionPerformed(evt);
            }
        });

        jBtn_cancelar.setBackground(java.awt.Color.red);
        jBtn_cancelar.setText("CANCELAR");
        jBtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cancelarActionPerformed(evt);
            }
        });

        jBtn_buscar.setText("BUSCAR");
        jBtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_generalLayout = new javax.swing.GroupLayout(jPanel_general);
        jPanel_general.setLayout(jPanel_generalLayout);
        jPanel_generalLayout.setHorizontalGroup(
            jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_generalLayout.createSequentialGroup()
                        .addComponent(jLabel_canso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_FragCanso, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_generalLayout.createSequentialGroup()
                        .addComponent(jBtn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane_cansons, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel_generalLayout.setVerticalGroup(
            jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_FragCanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_canso)
                    .addComponent(jBtn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_cansons, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBtn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_selecionarActionPerformed
        if(cansons!=null){
             id_can = cansons.get(jTable_cansons.getSelectedRow()).getId();
             setVisible(false);
             dispose();
        }
    }//GEN-LAST:event_jBtn_selecionarActionPerformed

    private void jBtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cancelarActionPerformed
             setVisible(false);
             //dispose();
    }//GEN-LAST:event_jBtn_cancelarActionPerformed

    private void jBtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_buscarActionPerformed
        setTaula();
    }//GEN-LAST:event_jBtn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cansons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cansons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cansons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cansons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cansons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_buscar;
    private javax.swing.JButton jBtn_cancelar;
    private javax.swing.JButton jBtn_selecionar;
    private javax.swing.JLabel jLabel_canso;
    private javax.swing.JPanel jPanel_general;
    private javax.swing.JScrollPane jScrollPane_cansons;
    private javax.swing.JTable jTable_cansons;
    private javax.swing.JTextField jTextField_FragCanso;
    // End of variables declaration//GEN-END:variables
}
